import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import {DatabaseSync} from 'node:sqlite';
import {mkdirSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const root=resolve(dirname(fileURLToPath(import.meta.url)),'..');
const dbPath=process.env.DB_PATH||resolve(root,'data','d3teams.sqlite');
mkdirSync(dirname(dbPath),{recursive:true});
const db=new DatabaseSync(dbPath);
db.exec(`PRAGMA foreign_keys=ON; PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS teams(id INTEGER PRIMARY KEY,name TEXT NOT NULL,slug TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,team_id INTEGER NOT NULL,name TEXT NOT NULL,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN ('owner','manager','mechanic','driver')),FOREIGN KEY(team_id) REFERENCES teams(id));
CREATE TABLE IF NOT EXISTS parts(id INTEGER PRIMARY KEY,team_id INTEGER NOT NULL,sku TEXT NOT NULL,name TEXT NOT NULL,category TEXT NOT NULL,base_qty INTEGER NOT NULL DEFAULT 0,truck_qty INTEGER NOT NULL DEFAULT 0,min_qty INTEGER NOT NULL DEFAULT 0,unit TEXT NOT NULL DEFAULT 'pcs',created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(team_id,sku),FOREIGN KEY(team_id) REFERENCES teams(id));
CREATE TABLE IF NOT EXISTS inventory_logs(id INTEGER PRIMARY KEY,team_id INTEGER NOT NULL,part_id INTEGER,actor_id INTEGER NOT NULL,type TEXT NOT NULL,description TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(team_id) REFERENCES teams(id),FOREIGN KEY(part_id) REFERENCES parts(id) ON DELETE SET NULL,FOREIGN KEY(actor_id) REFERENCES users(id));`);
if(!db.prepare("PRAGMA table_info(users)").all().some(c=>c.name==='active'))db.exec('ALTER TABLE users ADD COLUMN active INTEGER NOT NULL DEFAULT 1');
db.exec(`CREATE TABLE IF NOT EXISTS tasks(id INTEGER PRIMARY KEY,team_id INTEGER NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',priority TEXT NOT NULL CHECK(priority IN ('critical','high','medium','low')),status TEXT NOT NULL CHECK(status IN ('todo','progress','blocked','done')),due_date TEXT,assignee_id INTEGER,kart TEXT,event TEXT,checklist TEXT NOT NULL DEFAULT '[]',created_by INTEGER NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(team_id) REFERENCES teams(id),FOREIGN KEY(assignee_id) REFERENCES users(id) ON DELETE SET NULL,FOREIGN KEY(created_by) REFERENCES users(id));`);
db.exec(`CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY,team_id INTEGER NOT NULL,title TEXT NOT NULL,type TEXT NOT NULL CHECK(type IN ('race','test','training','meeting')),status TEXT NOT NULL CHECK(status IN ('planned','confirmed','completed','cancelled')),start_date TEXT NOT NULL,end_date TEXT NOT NULL,location TEXT NOT NULL DEFAULT '',track TEXT NOT NULL DEFAULT '',championship TEXT NOT NULL DEFAULT '',round TEXT NOT NULL DEFAULT '',arrival_time TEXT NOT NULL DEFAULT '',notes TEXT NOT NULL DEFAULT '',participants TEXT NOT NULL DEFAULT '[]',created_by INTEGER NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(team_id) REFERENCES teams(id),FOREIGN KEY(created_by) REFERENCES users(id));`);
for(const [name,sql] of [['pilot',"TEXT NOT NULL DEFAULT ''"],['race_class',"TEXT NOT NULL DEFAULT ''"],['mechanic',"TEXT NOT NULL DEFAULT ''"]])if(!db.prepare('PRAGMA table_info(events)').all().some(c=>c.name===name))db.exec(`ALTER TABLE events ADD COLUMN ${name} ${sql}`);
if(!db.prepare('PRAGMA table_info(events)').all().some(c=>c.name==='crew_entries'))db.exec("ALTER TABLE events ADD COLUMN crew_entries TEXT NOT NULL DEFAULT '[]'");

const seedParts=[['BRK-001','Brake pads CRG VEN 05','Brakes',0,0,4,'sets'],['CHN-219','Chain 219 O-Ring','Drivetrain',18,3,8,'pcs'],['OIL-001','Xeramic Racing Oil 1L','Fluids',12,4,6,'bottles'],['TYR-MG-R','MG Red slick tyres','Tyres',24,8,12,'tyres'],['TYR-MG-W','MG Wet tyres','Tyres',8,4,8,'tyres'],['SPK-NGK','NGK BR10EG spark plug','Engine',16,6,10,'pcs'],['SPR-80','Rear sprocket 80T','Drivetrain',5,2,4,'pcs'],['CBL-ACC','Accelerator cable complete','Controls',3,1,3,'pcs']];
if(!db.prepare('SELECT id FROM teams LIMIT 1').get()){
 const teamId=Number(db.prepare('INSERT INTO teams(name,slug) VALUES(?,?)').run('D3 Karting','d3-karting').lastInsertRowid);
 const initialPassword=process.env.INITIAL_OWNER_PASSWORD||'D3teams2026!';
 if(process.env.NODE_ENV==='production'&&!process.env.INITIAL_OWNER_PASSWORD)throw new Error('INITIAL_OWNER_PASSWORD is required in production');
 const hash=bcrypt.hashSync(initialPassword,10);
 db.prepare('INSERT INTO users(team_id,name,email,password_hash,role) VALUES(?,?,?,?,?)').run(teamId,process.env.INITIAL_OWNER_NAME||'Tony Kowalski',process.env.INITIAL_OWNER_EMAIL||'owner@d3teams.com',hash,'owner');
 const add=db.prepare('INSERT INTO parts(team_id,sku,name,category,base_qty,truck_qty,min_qty,unit) VALUES(?,?,?,?,?,?,?,?)');
 for(const p of seedParts)add.run(teamId,...p);
}
if(!db.prepare('SELECT id FROM tasks LIMIT 1').get()){
 const team=db.prepare('SELECT id FROM teams LIMIT 1').get(),owner=db.prepare("SELECT id FROM users WHERE role='owner' AND team_id=? LIMIT 1").get(team.id),mechanic=db.prepare("SELECT id FROM users WHERE role='mechanic' AND team_id=? LIMIT 1").get(team.id);
 const addTask=db.prepare('INSERT INTO tasks(team_id,title,description,priority,status,due_date,assignee_id,kart,event,checklist,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)');
 addTask.run(team.id,'Engine service · Kart 07','Complete engine inspection before Round 4.','critical','progress','2026-07-15',mechanic?.id||null,'Kart 07','Polish Championship · R4',JSON.stringify([{text:'Drain old oil',done:true},{text:'Inspect piston and ring',done:false},{text:'Dyno test',done:false}]),owner.id);
 addTask.run(team.id,'Front alignment · Kart 12','Set geometry to dry baseline.','high','todo','2026-07-14',mechanic?.id||null,'Kart 12','Polish Championship · R4',JSON.stringify([{text:'Check caster',done:false},{text:'Set toe',done:false}]),owner.id);
 addTask.run(team.id,'Prepare wet tyre set','Mount and label race wet tyres.','medium','todo','2026-07-17',mechanic?.id||null,'All karts','Polish Championship · R4','[]',owner.id);
}
if(!db.prepare('SELECT id FROM events LIMIT 1').get()){
 const team=db.prepare('SELECT id FROM teams LIMIT 1').get(),owner=db.prepare("SELECT id FROM users WHERE role='owner' AND team_id=? LIMIT 1").get(team.id),people=db.prepare('SELECT id FROM users WHERE team_id=? AND active=1').all(team.id).map(x=>x.id);
 const addEvent=db.prepare('INSERT INTO events(team_id,title,type,status,start_date,end_date,location,track,championship,round,arrival_time,notes,participants,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
 addEvent.run(team.id,'Polish Karting Championship · Round 4','race','confirmed','2026-07-18','2026-07-20','Słomczyn, Poland','Słomczyn Karting Circuit','Polish Karting Championship','Round 4','2026-07-17 16:00','Team truck departs Base at 09:00.',JSON.stringify(people),owner.id);
 addEvent.run(team.id,'Pre-race test · Słomczyn','test','planned','2026-08-04','2026-08-04','Słomczyn, Poland','Słomczyn Karting Circuit','','','2026-08-04 07:30','Dry setup validation.',JSON.stringify(people),owner.id);
 addEvent.run(team.id,'Technical team meeting','meeting','planned','2026-07-16','2026-07-16','D3 Base','Workshop','','','2026-07-16 18:00','Final readiness review.',JSON.stringify(people),owner.id);
}
db.prepare("UPDATE events SET pilot='Kacper Zieliński',race_class='Senior',mechanic='Marek Nowak' WHERE type IN ('race','test') AND pilot='' ").run();
db.prepare("UPDATE events SET pilot='—',race_class='Team',mechanic='Marek Nowak' WHERE type IN ('meeting','training') AND pilot='' ").run();
for(const e of db.prepare("SELECT id,pilot,race_class,mechanic,start_date,end_date FROM events WHERE crew_entries='[]'").all()){const days=Math.round((new Date(e.end_date)-new Date(e.start_date))/86400000)+1;db.prepare('UPDATE events SET crew_entries=? WHERE id=?').run(JSON.stringify([{pilot:e.pilot||'',raceClass:e.race_class||'',days,mechanic:e.mechanic||''}]),e.id)}
const allowedClasses=['OK','OKN','OKJ','OKNJ','KZ','Mini','Rotax Senior','Rotax Junior','ROK Senior','ROK Junior','ROK Mini','ROK Baby','Pokazy','Puffo'];
for(const e of db.prepare('SELECT id,crew_entries FROM events').all()){const rows=JSON.parse(e.crew_entries||'[]'),normalized=rows.map(r=>({...r,raceClass:allowedClasses.includes(r.raceClass)?r.raceClass:r.raceClass==='Junior'?'OKJ':r.raceClass==='Team'?'Pokazy':'OK'}));if(JSON.stringify(rows)!==JSON.stringify(normalized))db.prepare('UPDATE events SET crew_entries=? WHERE id=?').run(JSON.stringify(normalized),e.id)}

const app=express();
const allowedOrigins=(process.env.CORS_ORIGINS||'http://localhost:5173,http://127.0.0.1:5173')
 .split(',').map(origin=>origin.trim()).filter(Boolean);
app.use(cors({origin(origin,callback){
 if(!origin||allowedOrigins.includes(origin))return callback(null,true);
 return callback(new Error('Origin is not allowed by CORS'));
}}));
app.use(express.json({limit:'2mb'}));
const secret=process.env.JWT_SECRET||'d3teams-local-development-secret';
const auth=(req,res,next)=>{const token=req.headers.authorization?.replace('Bearer ','');try{req.user=jwt.verify(token,secret);next()}catch{return res.status(401).json({error:'Unauthorized'})}};
const roles=(...allowed)=>(req,res,next)=>allowed.includes(req.user.role)?next():res.status(403).json({error:'Insufficient permissions'});
const shape=p=>({id:p.id,sku:p.sku,name:p.name,category:p.category,base:p.base_qty,truck:p.truck_qty,min:p.min_qty,unit:p.unit});
const log=(user,partId,type,description)=>db.prepare('INSERT INTO inventory_logs(team_id,part_id,actor_id,type,description) VALUES(?,?,?,?,?)').run(user.teamId,partId,user.id,type,description);

app.get('/api/health',(_,res)=>res.json({status:'ok'}));
const normalizeEmail=value=>String(value||'').trim().toLowerCase();
const makeSlug=name=>String(name||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48)||'team';
app.post('/api/auth/register',(req,res)=>{
 const teamName=String(req.body.teamName||'').trim(),name=String(req.body.name||'').trim(),email=normalizeEmail(req.body.email),password=String(req.body.password||'');
 if(teamName.length<2||name.length<2||!/^\S+@\S+\.\S+$/.test(email))return res.status(400).json({error:'Please provide valid team, name and email details',code:'INVALID_DETAILS'});
 if(password.length<10||!/[a-z]/.test(password)||!/[A-Z]/.test(password)||!/[0-9]/.test(password))return res.status(400).json({error:'Password must have 10 characters, uppercase, lowercase and a number',code:'WEAK_PASSWORD'});
 if(db.prepare('SELECT id FROM users WHERE lower(email)=?').get(email))return res.status(409).json({error:'An account with this email already exists',code:'EMAIL_EXISTS'});
 let slug=makeSlug(teamName),suffix=1;
 while(db.prepare('SELECT id FROM teams WHERE slug=?').get(slug))slug=`${makeSlug(teamName)}-${++suffix}`;
 try{
  db.exec('BEGIN IMMEDIATE');
  const teamId=Number(db.prepare('INSERT INTO teams(name,slug) VALUES(?,?)').run(teamName,slug).lastInsertRowid);
  const userId=Number(db.prepare("INSERT INTO users(team_id,name,email,password_hash,role,active) VALUES(?,?,?,?, 'owner',1)").run(teamId,name,email,bcrypt.hashSync(password,12)).lastInsertRowid);
  db.exec('COMMIT');
  const profile={id:userId,teamId,name,email,role:'owner'};
  return res.status(201).json({token:jwt.sign(profile,secret,{expiresIn:'7d'}),user:profile,team:{id:teamId,name:teamName,slug}});
 }catch(error){
  try{db.exec('ROLLBACK')}catch{}
  return res.status(500).json({error:'Could not create the team account',code:'REGISTRATION_FAILED'});
 }
});
app.post('/api/auth/login',(req,res)=>{const user=db.prepare('SELECT * FROM users WHERE lower(email)=lower(?)').get(req.body.email||'');if(!user||!user.active||!bcrypt.compareSync(req.body.password||'',user.password_hash))return res.status(401).json({error:'Invalid email or password'});const profile={id:user.id,teamId:user.team_id,name:user.name,email:user.email,role:user.role};res.json({token:jwt.sign(profile,secret,{expiresIn:'7d'}),user:profile})});
app.get('/api/auth/me',auth,(req,res)=>res.json({user:req.user}));
const publicUser=u=>({id:u.id,name:u.name,email:u.email,role:u.role,active:!!u.active});
app.get('/api/team/users',auth,(req,res)=>res.json({users:db.prepare('SELECT id,name,email,role,active FROM users WHERE team_id=? ORDER BY role,name').all(req.user.teamId).map(publicUser)}));
app.post('/api/team/users',auth,roles('owner','manager'),(req,res)=>{const {name,email,password,role}=req.body,allowed=req.user.role==='owner'?['owner','manager','mechanic','driver']:['mechanic','driver'];if(!name||!email||!password||password.length<8||!allowed.includes(role))return res.status(400).json({error:'Invalid member data or role'});try{const id=Number(db.prepare('INSERT INTO users(team_id,name,email,password_hash,role,active) VALUES(?,?,?,?,?,1)').run(req.user.teamId,name,email,bcrypt.hashSync(password,10),role).lastInsertRowid);res.status(201).json({user:publicUser(db.prepare('SELECT id,name,email,role,active FROM users WHERE id=?').get(id))})}catch(e){res.status(400).json({error:e.message.includes('UNIQUE')?'Email already exists':'Could not create member'})}});
app.put('/api/team/users/:id',auth,roles('owner','manager'),(req,res)=>{const target=db.prepare('SELECT * FROM users WHERE id=? AND team_id=?').get(req.params.id,req.user.teamId);if(!target)return res.status(404).json({error:'Member not found'});if(target.id===req.user.id&&req.body.active===false)return res.status(400).json({error:'You cannot deactivate yourself'});if(req.user.role==='manager'&&['owner','manager'].includes(target.role))return res.status(403).json({error:'Managers cannot modify owners or managers'});const allowed=req.user.role==='owner'?['owner','manager','mechanic','driver']:['mechanic','driver'];if(!allowed.includes(req.body.role))return res.status(400).json({error:'Invalid role'});db.prepare('UPDATE users SET name=?,role=?,active=? WHERE id=? AND team_id=?').run(req.body.name,req.body.role,req.body.active?1:0,target.id,req.user.teamId);res.json({user:publicUser(db.prepare('SELECT id,name,email,role,active FROM users WHERE id=?').get(target.id))})});
app.delete('/api/team/users/:id',auth,roles('owner'),(req,res)=>{if(+req.params.id===req.user.id)return res.status(400).json({error:'You cannot delete yourself'});const result=db.prepare('DELETE FROM users WHERE id=? AND team_id=?').run(req.params.id,req.user.teamId);if(!result.changes)return res.status(404).json({error:'Member not found'});res.status(204).end()});
const taskSelect=`SELECT t.*,u.name assignee_name FROM tasks t LEFT JOIN users u ON u.id=t.assignee_id WHERE t.team_id=?`;
const taskShape=t=>({...t,checklist:JSON.parse(t.checklist||'[]'),assignee:t.assignee_id?{id:t.assignee_id,name:t.assignee_name}:null});
app.get('/api/tasks',auth,(req,res)=>res.json({tasks:db.prepare(taskSelect+' ORDER BY CASE t.status WHEN \'progress\' THEN 1 WHEN \'todo\' THEN 2 WHEN \'blocked\' THEN 3 ELSE 4 END,t.due_date').all(req.user.teamId).map(taskShape)}));
app.post('/api/tasks',auth,roles('owner','manager'),(req,res)=>{const t=req.body;if(!t.title||!['critical','high','medium','low'].includes(t.priority)||!['todo','progress','blocked','done'].includes(t.status))return res.status(400).json({error:'Invalid task data'});const id=Number(db.prepare('INSERT INTO tasks(team_id,title,description,priority,status,due_date,assignee_id,kart,event,checklist,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(req.user.teamId,t.title,t.description||'',t.priority,t.status,t.dueDate||null,t.assigneeId||null,t.kart||'',t.event||'',JSON.stringify(t.checklist||[]),req.user.id).lastInsertRowid);res.status(201).json({task:taskShape(db.prepare(taskSelect+' AND t.id=?').get(req.user.teamId,id))})});
app.put('/api/tasks/:id',auth,roles('owner','manager'),(req,res)=>{const t=req.body,old=db.prepare('SELECT id FROM tasks WHERE id=? AND team_id=?').get(req.params.id,req.user.teamId);if(!old)return res.status(404).json({error:'Task not found'});db.prepare("UPDATE tasks SET title=?,description=?,priority=?,status=?,due_date=?,assignee_id=?,kart=?,event=?,checklist=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND team_id=?").run(t.title,t.description||'',t.priority,t.status,t.dueDate||null,t.assigneeId||null,t.kart||'',t.event||'',JSON.stringify(t.checklist||[]),req.params.id,req.user.teamId);res.json({task:taskShape(db.prepare(taskSelect+' AND t.id=?').get(req.user.teamId,req.params.id))})});
app.patch('/api/tasks/:id/progress',auth,roles('owner','manager','mechanic'),(req,res)=>{const t=db.prepare('SELECT * FROM tasks WHERE id=? AND team_id=?').get(req.params.id,req.user.teamId);if(!t)return res.status(404).json({error:'Task not found'});if(req.user.role==='mechanic'&&t.assignee_id!==req.user.id)return res.status(403).json({error:'Task is assigned to another member'});const status=req.body.status||t.status,checklist=req.body.checklist||JSON.parse(t.checklist);if(!['todo','progress','blocked','done'].includes(status))return res.status(400).json({error:'Invalid status'});db.prepare("UPDATE tasks SET status=?,checklist=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").run(status,JSON.stringify(checklist),t.id);res.json({task:taskShape(db.prepare(taskSelect+' AND t.id=?').get(req.user.teamId,t.id))})});
app.delete('/api/tasks/:id',auth,roles('owner','manager'),(req,res)=>{const result=db.prepare('DELETE FROM tasks WHERE id=? AND team_id=?').run(req.params.id,req.user.teamId);if(!result.changes)return res.status(404).json({error:'Task not found'});res.status(204).end()});
const eventShape=(e,teamId)=>{const ids=JSON.parse(e.participants||'[]');const people=ids.length?db.prepare(`SELECT id,name,role FROM users WHERE team_id=? AND id IN (${ids.map(()=>'?').join(',')})`).all(teamId,...ids):[];return {...e,crewEntries:JSON.parse(e.crew_entries||'[]'),participants:people,participantIds:ids,taskCount:db.prepare('SELECT count(*) count FROM tasks WHERE team_id=? AND event=?').get(teamId,e.title).count}};
app.get('/api/events',auth,(req,res)=>res.json({events:db.prepare('SELECT * FROM events WHERE team_id=? ORDER BY start_date').all(req.user.teamId).map(e=>eventShape(e,req.user.teamId))}));
app.post('/api/events',auth,roles('owner','manager'),(req,res)=>{const e=req.body;if(!e.title||!e.startDate||!e.endDate||!['race','test','training','meeting'].includes(e.type))return res.status(400).json({error:'Invalid event data'});const id=Number(db.prepare('INSERT INTO events(team_id,title,type,status,start_date,end_date,location,track,championship,round,arrival_time,notes,participants,crew_entries,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(req.user.teamId,e.title,e.type,e.status||'planned',e.startDate,e.endDate,e.location||'',e.track||'',e.championship||'',e.round||'',e.arrivalTime||'',e.notes||'',JSON.stringify(e.participantIds||[]),JSON.stringify(e.crewEntries||[]),req.user.id).lastInsertRowid);res.status(201).json({event:eventShape(db.prepare('SELECT * FROM events WHERE id=?').get(id),req.user.teamId)})});
app.put('/api/events/:id',auth,roles('owner','manager'),(req,res)=>{const e=req.body,old=db.prepare('SELECT id FROM events WHERE id=? AND team_id=?').get(req.params.id,req.user.teamId);if(!old)return res.status(404).json({error:'Event not found'});db.prepare("UPDATE events SET title=?,type=?,status=?,start_date=?,end_date=?,location=?,track=?,championship=?,round=?,arrival_time=?,notes=?,participants=?,crew_entries=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND team_id=?").run(e.title,e.type,e.status,e.startDate,e.endDate,e.location||'',e.track||'',e.championship||'',e.round||'',e.arrivalTime||'',e.notes||'',JSON.stringify(e.participantIds||[]),JSON.stringify(e.crewEntries||[]),req.params.id,req.user.teamId);res.json({event:eventShape(db.prepare('SELECT * FROM events WHERE id=?').get(req.params.id),req.user.teamId)})});
app.delete('/api/events/:id',auth,roles('owner','manager'),(req,res)=>{const result=db.prepare('DELETE FROM events WHERE id=? AND team_id=?').run(req.params.id,req.user.teamId);if(!result.changes)return res.status(404).json({error:'Event not found'});res.status(204).end()});
app.get('/api/parts',auth,(req,res)=>res.json({parts:db.prepare('SELECT * FROM parts WHERE team_id=? ORDER BY name').all(req.user.teamId).map(shape)}));
app.post('/api/parts',auth,roles('owner','manager'),(req,res)=>{const p=req.body;try{const id=Number(db.prepare('INSERT INTO parts(team_id,sku,name,category,base_qty,truck_qty,min_qty,unit) VALUES(?,?,?,?,?,?,?,?)').run(req.user.teamId,p.sku,p.name,p.category,p.base||0,p.truck||0,p.min||0,p.unit||'pcs').lastInsertRowid);log(req.user,id,'create',`${p.name} · created`);res.status(201).json({part:shape(db.prepare('SELECT * FROM parts WHERE id=?').get(id))})}catch(e){res.status(400).json({error:e.message.includes('UNIQUE')?'SKU already exists':'Invalid part data'})}});
app.put('/api/parts/:id',auth,roles('owner','manager'),(req,res)=>{const p=req.body;const old=db.prepare('SELECT * FROM parts WHERE id=? AND team_id=?').get(req.params.id,req.user.teamId);if(!old)return res.status(404).json({error:'Part not found'});db.prepare("UPDATE parts SET name=?,category=?,base_qty=?,truck_qty=?,min_qty=?,unit=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND team_id=?").run(p.name,p.category,p.base,p.truck,p.min,p.unit,req.params.id,req.user.teamId);log(req.user,+req.params.id,'edit',`${p.name} · edited`);res.json({part:shape(db.prepare('SELECT * FROM parts WHERE id=?').get(req.params.id))})});
app.delete('/api/parts/:id',auth,roles('owner','manager'),(req,res)=>{const p=db.prepare('SELECT * FROM parts WHERE id=? AND team_id=?').get(req.params.id,req.user.teamId);if(!p)return res.status(404).json({error:'Part not found'});log(req.user,p.id,'delete',`${p.name} · deleted`);db.prepare('DELETE FROM parts WHERE id=? AND team_id=?').run(p.id,req.user.teamId);res.status(204).end()});
app.post('/api/parts/:id/move',auth,roles('owner','manager','mechanic'),(req,res)=>{const p=db.prepare('SELECT * FROM parts WHERE id=? AND team_id=?').get(req.params.id,req.user.teamId);const qty=Math.max(0,+req.body.qty||0),from=req.body.from,to=from==='base'?'truck':'base';if(!p)return res.status(404).json({error:'Part not found'});if(!['base','truck'].includes(from)||!qty||p[`${from}_qty`]<qty)return res.status(400).json({error:'Invalid quantity'});db.prepare(`UPDATE parts SET ${from}_qty=${from}_qty-?,${to}_qty=${to}_qty+?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(qty,qty,p.id);log(req.user,p.id,'move',`${qty} × ${p.name} · ${from==='base'?'Base → Truck':'Truck → Base'}`);res.json({part:shape(db.prepare('SELECT * FROM parts WHERE id=?').get(p.id))})});
app.post('/api/parts/:id/adjust',auth,roles('owner','manager','mechanic'),(req,res)=>{const p=db.prepare('SELECT * FROM parts WHERE id=? AND team_id=?').get(req.params.id,req.user.teamId),loc=req.body.location,delta=+req.body.delta||0;if(!p)return res.status(404).json({error:'Part not found'});if(!['base','truck'].includes(loc)||p[`${loc}_qty`]+delta<0)return res.status(400).json({error:'Invalid adjustment'});db.prepare(`UPDATE parts SET ${loc}_qty=${loc}_qty+?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).run(delta,p.id);log(req.user,p.id,'adjust',`${delta>0?'+':''}${delta} × ${p.name} · ${loc==='base'?'Base':'Truck'}`);res.json({part:shape(db.prepare('SELECT * FROM parts WHERE id=?').get(p.id))})});
app.get('/api/inventory/logs',auth,(req,res)=>res.json({logs:db.prepare('SELECT description,created_at FROM inventory_logs WHERE team_id=? ORDER BY id DESC LIMIT 10').all(req.user.teamId)}));
const port=Number(process.env.PORT)||3001;
app.listen(port,'0.0.0.0',()=>console.log(`D3Teams API listening on port ${port}`));
